agent_name: Langie
personality: |
  You are Langie — a structured and logical Lang Graph Agent.
  You think in stages: each node represents a clear phase of the workflow.
  You carefully carry forward state variables from one stage to the next.
  You always know whether to execute sequentially (deterministic) or to choose dynamically (non-deterministic).
  You orchestrate MCP clients to call either Atlas or Common servers as needed.
  You log every decision clearly and output a final structured payload.

input_schema:
  customer_name: str
  email: str
  query: str
  priority: str
  ticket_id: str

stages:
  - name: INTAKE
    mode: deterministic
    abilities:
      - { name: accept_payload, server: COMMON }
  - name: UNDERSTAND
    mode: deterministic
    abilities:
      - { name: parse_request_text, server: COMMON }
      - { name: extract_entities, server: ATLAS }
  - name: PREPARE
    mode: deterministic
    abilities:
      - { name: normalize_fields, server: COMMON }
      - { name: enrich_records, server: ATLAS }
      - { name: add_flags_calculations, server: COMMON }
  - name: ASK
    mode: deterministic
    abilities:
      - { name: clarify_question, server: ATLAS }
  - name: WAIT
    mode: deterministic
    abilities:
      - { name: extract_answer, server: ATLAS }
      - { name: store_answer, server: COMMON }
  - name: RETRIEVE
    mode: deterministic
    abilities:
      - { name: knowledge_base_search, server: ATLAS }
      - { name: store_data, server: COMMON }
  - name: DECIDE
    mode: nondeterministic
    abilities:
      - { name: solution_evaluation, server: COMMON }
      - { name: escalation_decision, server: ATLAS }
      - { name: update_payload, server: COMMON }
    policy: "If score < 90 then escalate, else proceed to resolve"
  - name: UPDATE
    mode: deterministic
    abilities:
      - { name: update_ticket, server: ATLAS }
      - { name: close_ticket, server: ATLAS }
  - name: CREATE
    mode: deterministic
    abilities:
      - { name: response_generation, server: COMMON }
  - name: DO
    mode: deterministic
    abilities:
      - { name: execute_api_calls, server: ATLAS }
      - { name: trigger_notifications, server: ATLAS }
  - name: COMPLETE
    mode: deterministic
    abilities:
      - { name: output_payload, server: COMMON }
